plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '0.1.0-alpha'
group = 'com.fontainerepublic'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'fontainerepublic'
            mods {
                fontainerepublic {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'fontainerepublic'
            mods {
                fontainerepublic {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.18'
}

tasks.withType(ProcessResources).configureEach {
    filesMatching('META-INF/mods.toml') {
        expand(version: project.version)
    }
}

// 锁定 Forge 版本，升级需显式修改
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
