package com.fontainerepublic.server.parliament.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent bill identity (FR-PAR-001-A §3.3).
 *
 * <p>A {@code BillId} is generated by the server from an injected UUID
 * source when a ballot passes and is immutable once issued. It is never
 * selected by a client.</p>
 */
public record BillId(UUID value) {

    public BillId {
        Objects.requireNonNull(value, "value");
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("BillId must be a canonical UUID");
        }
    }

    public static BillId of(UUID value) {
        return new BillId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
