package com.fontainerepublic.server.parliament.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent proposal identity (FR-PAR-001-A §3.1).
 *
 * <p>A {@code ProposalId} is generated by the server from an injected UUID
 * source, is never selected by a client, and is immutable once a proposal is
 * submitted. Its UUID representation is an internal storage choice only and
 * never implies a player UUID or a public number.</p>
 */
public record ProposalId(UUID value) {

    public ProposalId {
        Objects.requireNonNull(value, "value");
        // UUID.toString() is always lowercase canonical; keep the invariant
        // explicit so a non-canonical representation can never be stored.
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("ProposalId must be a canonical UUID");
        }
    }

    public static ProposalId of(UUID value) {
        return new ProposalId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
