package com.fontainerepublic.server.parliament.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent ballot identity (FR-PAR-001-A §3.2).
 *
 * <p>A {@code VoteId} is generated by the server from an injected UUID
 * source at vote open and is immutable once issued. It is never selected by
 * a client.</p>
 */
public record VoteId(UUID value) {

    public VoteId {
        Objects.requireNonNull(value, "value");
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("VoteId must be a canonical UUID");
        }
    }

    public static VoteId of(UUID value) {
        return new VoteId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
