package com.fontainerepublic.server.land.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent parcel identity (FR-LAND-001-A §3.1).
 *
 * <p>A {@code ParcelId} is generated by the server from an injected UUID
 * source, is never selected by a client, and is immutable once a parcel is
 * created. Its UUID representation is an internal storage choice only and
 * never implies a player UUID or a public number.</p>
 */
public record ParcelId(UUID value) {

    public ParcelId {
        Objects.requireNonNull(value, "value");
        // UUID.toString() is always lowercase canonical; keep the invariant
        // explicit so a non-canonical representation can never be stored.
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("ParcelId must be a canonical UUID");
        }
    }

    public static ParcelId of(UUID value) {
        return new ParcelId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
