package com.fontainerepublic.server.registry.model;

import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent subject identity (FR-ID-001-A §3.1/§3.2).
 *
 * <p>A {@code SubjectId} is generated by the server from an injected UUID
 * source, is never selected by a client, and is the internal foreign key used
 * between server modules. Its UUID representation is an internal storage
 * choice only — it is deliberately distinct from the public
 * {@link RegistryNumber} and never implies a player UUID.</p>
 */
public record SubjectId(UUID value) {

    public SubjectId {
        Objects.requireNonNull(value, "value");
        // UUID.toString() is always lowercase canonical; keep the invariant
        // explicit so a non-canonical representation can never be stored.
        if (!value.toString().equals(value.toString().toLowerCase(java.util.Locale.ROOT))) {
            throw new IllegalArgumentException("SubjectId must be a canonical UUID");
        }
    }

    public static SubjectId of(UUID value) {
        return new SubjectId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage/digest key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
