package com.fontainerepublic.server.justice.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent case identity (FR-JUS-001-A §3.1).
 *
 * <p>A {@code CaseId} is generated by the server from an injected UUID
 * source at filing/intake and is immutable once issued. It is never selected
 * by a client.</p>
 */
public record CaseId(UUID value) {

    public CaseId {
        Objects.requireNonNull(value, "value");
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("CaseId must be a canonical UUID");
        }
    }

    public static CaseId of(UUID value) {
        return new CaseId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
