package com.fontainerepublic.server.justice.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent evidence identity (FR-JUS-001-A §3.2).
 *
 * <p>An {@code EvidenceId} is generated by the server from an injected UUID
 * source on submission and is immutable once issued. It is never selected by
 * a client.</p>
 */
public record EvidenceId(UUID value) {

    public EvidenceId {
        Objects.requireNonNull(value, "value");
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("EvidenceId must be a canonical UUID");
        }
    }

    public static EvidenceId of(UUID value) {
        return new EvidenceId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
