package com.fontainerepublic.server.justice.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent verdict identity (FR-JUS-001-A §3.3).
 *
 * <p>A {@code VerdictId} is generated by the server from an injected UUID
 * source when a verdict is issued and is immutable once issued. It is never
 * selected by a client.</p>
 */
public record VerdictId(UUID value) {

    public VerdictId {
        Objects.requireNonNull(value, "value");
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("VerdictId must be a canonical UUID");
        }
    }

    public static VerdictId of(UUID value) {
        return new VerdictId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
