package com.fontainerepublic.server.institutionaccess.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent terminal identity (FR-INST-002-A §3).
 *
 * <p>A {@code TerminalId} is generated by the server from an injected UUID
 * source, is never selected by a client, and is immutable once a terminal is
 * registered. Its UUID representation is an internal storage choice only and
 * never implies a player UUID or a public number.</p>
 */
public record TerminalId(UUID value) {

    public TerminalId {
        Objects.requireNonNull(value, "value");
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("TerminalId must be a canonical UUID");
        }
    }

    public static TerminalId of(UUID value) {
        return new TerminalId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
