package com.fontainerepublic.server.institutionaccess.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent zone identity (FR-INST-002-B §2).
 *
 * <p>A {@code ZoneId} is generated by the server from an injected UUID
 * source, is never selected by a client, and is immutable once a zone is
 * registered. Its UUID representation is an internal storage choice only and
 * never implies a player UUID or a public number.</p>
 */
public record ZoneId(UUID value) {

    public ZoneId {
        Objects.requireNonNull(value, "value");
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("ZoneId must be a canonical UUID");
        }
    }

    public static ZoneId of(UUID value) {
        return new ZoneId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
