package com.fontainerepublic.server.government.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent ministry identity (FR-GOV-001-A §3.2).
 *
 * <p>A {@code MinistryId} is generated by the server from an injected UUID
 * source, is never selected by a client, and is immutable once a ministry is
 * created. Its UUID representation is an internal storage choice only and
 * never implies a player UUID or a public number.</p>
 */
public record MinistryId(UUID value) {

    public MinistryId {
        Objects.requireNonNull(value, "value");
        // UUID.toString() is always lowercase canonical; keep the invariant
        // explicit so a non-canonical representation can never be stored.
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("MinistryId must be a canonical UUID");
        }
    }

    public static MinistryId of(UUID value) {
        return new MinistryId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
