package com.fontainerepublic.server.government.model;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;

/**
 * Opaque internal permanent government-position identity (FR-GOV-001-A §3.1).
 *
 * <p>A {@code PositionId} is generated by the server from an injected UUID
 * source, is never selected by a client, and is immutable once a position is
 * created. Its UUID representation is an internal storage choice only and
 * never implies a player UUID or a public number.</p>
 */
public record PositionId(UUID value) {

    public PositionId {
        Objects.requireNonNull(value, "value");
        if (!value.toString().equals(value.toString().toLowerCase(Locale.ROOT))) {
            throw new IllegalArgumentException("PositionId must be a canonical UUID");
        }
    }

    public static PositionId of(UUID value) {
        return new PositionId(value);
    }

    /** Canonical lowercase hyphenated form used as the storage key. */
    public String canonicalKey() {
        return value.toString();
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
